name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Swift on Linux
      uses: sersoft-gmbh/swifty-linux-action@v2.1
      with:
        release-version: 5.7
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -c release -v
    - name: Run tests
      run: swift test -v
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Tlox
        path: .build/**/release/Tlox
        retention-days: 1
