name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: swift-actions/setup-swift@v1.18.0
    - name: Get swift version
      run: swift --version
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -c release -v
    - name: Run tests
      run: swift test -v
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Tlox
        path: .build/**/release/Tlox
        retention-days: 1
